version: '2'

services:
  mindex:
    build: .
    volumes:
      - .:/code
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  kibana: # https://www.elastic.co/guide/en/kibana/current/_configuring_kibana_on_docker.html
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"
